name: Kolab CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: kolab

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.6 

    - name: Install dependencies
      run: |
        gem install bundler
        bundle update xpath
        bundle update capybara
        bundle install --jobs 4 --retry 3

    - name: Run RuboCop
      run: bundle exec rubocop

  setup:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: kolab

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.6 

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Setup Rails
      run: |
        cp config/database.yml.ci config/database.yml
        bundle exec rails db:create
        bundle exec rails db:schema:load
        bundle exec rails db:seed
